name: blockchain_monitor
description: A high level blockchain monitoring library.
version: 0.1.0
homepage: https://github.com/inacta/blockchain_monitor

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  blockchair: ^0.1.2
  blockchain_info: ^0.1.3
  blockbook: ^1.1.4
  blockcypher: ^0.3.0
  logger: ^0.8.3
  retry: ^3.0.0
  equatable: ^1.0.2

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
  mockito: ^4.1.1
