name: dart

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: pub get
    - name: Run tests
      run: pub run test
    - name: Format
      run: dartfmt -n --set-exit-if-changed .
    - name: Linter
      run: dartanalyzer . --options=analysis_options.yaml --fatal-hints
